# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Release Project

permissions:
  contents: read

# This workflow is triggered manually from the Actions tab.
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release'
        required: true
        type: string
      continue_if_tag_exists:
        description: 'Continue the workflow even if the GitHub tag already exists'
        type: boolean
        required: true
        default: false

jobs:
  create_git_tag:
    runs-on: ubuntu-latest
    permissions:
      # Required for creating and pushing git tags.
      contents: write
    steps:
      - name: Checkout current commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if on Master Branch
        run: |
          if ! git merge-base --is-ancestor "${{ github.ref }}" "refs/remotes/origin/master"; then
            echo "Error: Releases can only be created from commits that are on the 'master' branch."
            exit 1
          fi
      - name: Check and Create Git Tag
        run: |
          TAG_NAME="${{ inputs.version }}"
          # Get all remote refs matching the TAG_NAME
          ALL_REFS=$(git ls-remote origin "$TAG_NAME")

          # Check if any refs were found and if we should continue
          if [ -n "${ALL_REFS}" ]; then
            # Check if this is a tag reference
            if echo "${ALL_REFS}" | grep -q "refs/tags/${TAG_NAME}"; then
              echo "Tag '$TAG_NAME' already exists."
              if [[ "${{ inputs.continue_if_tag_exists }}" == "true" ]]; then
                echo "Continuing workflow as 'continue_if_tag_exists' is true. Skipping tag creation."
                exit 0
              else
                echo "Error: Tag '$TAG_NAME' already exists and 'continue_if_tag_exists' is false. Aborting."
                exit 1
              fi
            else
              echo "A ref with name '${TAG_NAME}' exists but is not a tag (e.g., a branch). Aborting."
              exit 1
            fi
          fi

          echo "Creating tag '$TAG_NAME'"

          git config --local user.email "rules-closure-github-bot@github.com"
          git config --local user.name "Rules Closure GitHub Bot"
          git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
          git push origin "$TAG_NAME"

  release:
    needs: create_git_tag
    permissions:
      # Permissions for creating a github release.
      contents: write
      # Permissions for publishing to bcr.
      id-token: write
      attestations: write
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.2.3
    with:
      prerelease: false
      release_files: rules_closure-*.tar.gz
      tag_name: ${{ inputs.version }}
      # TODO(dramaix): contribute upstream to allow skipping test.
      bazel_test_command: "bazel build"

  publish_to_bcr:
    needs: release
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v0.2.3
    with:
      tag_name: ${{ inputs.version }}
      registry_fork: j2cl-github-bot/bazel-central-registry
      attest: true
      author_name: j2cl-github-bot
      author_email: j2cl-github-bot@google.com
      # The PR is authored by a bot account, which requires team member approval. Therefore, we
      # don't need to create it as a draft.
      draft: false
    permissions:
      contents: write
      id-token: write
      attestations: write
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
